(function(){var CATS=["☰ সব ক্যাটাগরি","ইলেকট্রনিক্স","ফ্যাশন ও পোশাক","হোম ও লিভিং","খেলাধুলা","বিউটি ও কেয়ার","শিশু ও খেলনা","হোলসেল রেট"];var TRENDING=[{icon:"⌚",title:"স্মার্ট ওয়াচ — ওয়াটারপ্রুফ, লং ব্যাটারি",price:"৳৮৫০",meta:"১০০+ বিক্রি"},{icon:"🎧",title:"ওয়্যারলেস হেডফোন — নয়েজ ক্যান্সেলিং",price:"৳৯৯০",meta:"৩ বছর সাপ্লায়ার"},{icon:"🧥",title:"উইন্টার জ্যাকেট — সব সাইজ পাওয়া যায়",price:"৳১,২০০",meta:"হোলসেল MOQ ৫"},{icon:"🪑",title:"অফিস চেয়ার — এরগনোমিক ডিজাইন",price:"৳৩,৫০০",meta:"ফ্রি শিপিং"},{icon:"🧸",title:"সফট টয় — বাচ্চাদের জন্য উপহার",price:"৳৩৫০",meta:"MOQ ১০"}];var RECENT=[{icon:"👟",title:"স্পোর্টস জুতা — আরামদায়ক ও টেকসই",price:"৳৭৫০",meta:"৫০+ বিক্রি"},{icon:"💡",title:"LED লাইট সেট — এনার্জি সেভিং",price:"৳২২০",meta:"হোলসেল রেট"},{icon:"🎒",title:"ব্যাকপ্যাক — ওয়াটারপ্রুফ ফেব্রিক",price:"৳৬৫০",meta:"ফ্রি স্যাম্পল"},{icon:"🧴",title:"স্কিন কেয়ার সেট — অরগ্যানিক উপাদান",price:"৳৪৫০",meta:"৩ বছর সাপ্লায়ার"},{icon:"📱",title:"ফোন কেস — শকপ্রুফ কভার",price:"৳১৫০",meta:"MOQ ২০"}];var FOOTER=[{h:"Daran Shop সম্পর্কে",links:["আমাদের কথা","ক্যারিয়ার","যোগাযোগ"]},{h:"ক্রেতাদের জন্য",links:["অর্ডার ট্র্যাক করুন","রিটার্ন পলিসি","পেমেন্ট পদ্ধতি"]},{h:"বিক্রেতাদের জন্য",links:["বিক্রেতা হোন","সাপ্লায়ার লগইন","বিক্রেতা গাইড"]},{h:"সহায়তা",links:["হেল্প সেন্টার","নিরাপত্তা নীতি","শর্তাবলী"]}];function cardHTML(p){return'<div class="ds-card"><div class="ds-card-img">'+p.icon+'</div>'+
'<div class="ds-card-body"><p class="ds-card-title">'+p.title+'</p>'+
'<div class="ds-card-price">'+p.price+' <span>/ পিস</span></div>'+
'<div class="ds-card-meta"><span class="ds-badge">Verified</span> '+p.meta+'</div></div></div>';}
function render(){var catBox=document.getElementById('ds-catnav-list');if(catBox){catBox.innerHTML=CATS.map(function(c,i){return'<a href="#">'+c+'</a>';}).join('');}
var t=document.getElementById('ds-grid-trending');if(t){t.innerHTML=TRENDING.map(cardHTML).join('');}
var r=document.getElementById('ds-grid-recent');if(r){r.innerHTML=RECENT.map(cardHTML).join('');}
var f=document.getElementById('ds-footer-cols');if(f){f.innerHTML=FOOTER.map(function(col){return'<div><h4>'+col.h+'</h4><ul>'+
col.links.map(function(l){return'<li><a href="#">'+l+'</a></li>';}).join('')+
'</ul></div>';}).join('');}}
function bindSearch(){var root=document.getElementById('ds-root');if(!root)return;var form=root.querySelector('.ds-search');if(!form)return;form.addEventListener('submit',function(e){e.preventDefault();var q=form.querySelector('input').value.trim();if(q){alert('সার্চ করা হচ্ছে: '+q);}});}
render();bindSearch();})();